### ISSUE TITLE
Error: Invalid export data. Please provide an array of object

### ISSUE THREAD

**Issue by garg10may** [zheeeng/export-from-json#110]
Error: Invalid export data. Please provide an array of object
for a valid object

**Comment by zheeeng** [comment]
can you provide a sample data?

**Comment by garg10may** [comment]
```
{
                        'Test Cohort Version': ppcNumber,
                        'Study': study,
                        'Category': changeCategoryUatMeMap[row.changeCategory],
                        'CheckId': row.checkId,
                        'Description': 'f',
                        'Instructions': 'sdfds'
                      }
```

**Comment by zheeeng** [comment]
Can't reproduce your case. You can fork a repro on https://codepen.io/zheeeng/pen/PQxBKr, I will dig into your issue.

**Comment by subhadeepchakraborty** [comment]
any update?

**Comment by zheeeng** [comment]
This example https://codepen.io/zheeeng/pen/PQxBKr is using your sample data. Can you provide a more concrete example?

**Comment by subhadeepchakraborty** [comment]
I am using the same json structure

**Comment by zheeeng** [comment]
This example works correctly. If any reproduction can be provided will be much helpful to resolve your problem.

**Comment by atakanyurttutann** [comment]
Help me

**Comment by zheeeng** [comment]
> Help me. I am having the same problem

Please provide repro for contributing debug.

**Comment by rajukumar-rjk** [comment]
I am facing the same issue.  check the screenshot. It's correct data types.  
<img width="938" alt="image" src="https://user-images.githubusercontent.com/25051437/182061828-27625498-3356-4983-8e09-755e716b69ef.png">

**Comment by rajukumar-rjk** [comment]
> I am facing the same issue. check the screenshot. It's correct data types. <img alt="image" width="938" src="https://user-images.githubusercontent.com/25051437/182061828-27625498-3356-4983-8e09-755e716b69ef.png">

I am using it with react

**Comment by zheeeng** [comment]
@rajukumar-rjk Hey, thx for using. Would you mind posting your sample data here for contributing debug this issue? https://codesandbox.io/s/test-export-from-json-p9qgz2

**Comment by rajukumar-rjk** [comment]
> @rajukumar-rjk Hey, thx for using. Would you mind posting your sample data here for contributing debug this issue? https://codesandbox.io/s/test-export-from-json-p9qgz2

It worked there. but it gives error when I use same data in the react project. I have attached the json
[exportFromJsonData.txt](https://github.com/zheeeng/export-from-json/files/9231051/exportFromJsonData.txt)

**Comment by zheeeng** [comment]
> > @rajukumar-rjk Hey, thx for using. Would you mind posting your sample data here for contributing debug this issue? https://codesandbox.io/s/test-export-from-json-p9qgz2
> 
> It worked there. but it gives error when I use same data in the react project. I have attached the json [exportFromJsonData.txt](https://github.com/zheeeng/export-from-json/files/9231051/exportFromJsonData.txt)

Is there some wrapped data structure passed? For example an reactive data created by Mobx or others?

**Comment by rajukumar-rjk** [comment]
> > > @rajukumar-rjk Hey, thx for using. Would you mind posting your sample data here for contributing debug this issue? https://codesandbox.io/s/test-export-from-json-p9qgz2
> > 
> > 
> > It worked there. but it gives error when I use same data in the react project. I have attached the json [exportFromJsonData.txt](https://github.com/zheeeng/export-from-json/files/9231051/exportFromJsonData.txt)
> 
> Is there some wrapped data structure passed? For example, reactive data created by Mobx or others?

No. it just simple array, exactly what I have shared with you.

**Comment by zheeeng** [comment]
@rajukumar-rjk eport-from-json asserts input data is `Array` via such implementation `https://github.com/zheeeng/export-from-json/blob/master/src/utils.ts#L1-L3`, if possible you can try test your input's type.

**Comment by ricko-v** [comment]
@garg10may try this
`
let data = [
    {
        "Test Cohort Version": "5",
        "Study": "CINC280X2105C",
        "Category": "Screen Testing",
        "CheckId": "sdfsdf",
        "Description": "f",
        "Instructions": "sdfds"
    },
    {
        "Test Cohort Version": "5",
        "Study": "CINC280X2105C",
        "Category": "Screen Testing",
        "CheckId": "sfadsfds",
        "Description": "f",
        "Instructions": "sdfds"
    }
]

let fileName = 'example'
let exportType = exportFromJSON.types.xls;
exportFromJSON({ data: data, fileName: fileName, exportType: exportType })
`

it's work in my case

**Comment by rajukumar-rjk** [comment]
> @garg10may try this
> 
> ```js
> let data = [
>     {
>         "Test Cohort Version": "5",
>         "Study": "CINC280X2105C",
>         "Category": "Screen Testing",
>         "CheckId": "sdfsdf",
>         "Description": "f",
>         "Instructions": "sdfds"
>     },
>     {
>         "Test Cohort Version": "5",
>         "Study": "CINC280X2105C",
>         "Category": "Screen Testing",
>         "CheckId": "sfadsfds",
>         "Description": "f",
>         "Instructions": "sdfds"
>     }
> ]
> 
> let fileName = 'example'
> let exportType = exportFromJSON.types.xls;
> exportFromJSON({ data: data, fileName: fileName, exportType: exportType })
> ```
> 
> it's work in my case

This solve my problem too.

**Comment by PaulleDemon** [comment]
Arrays are a special type of object. The typeof operator in JavaScript returns "object" for arrays. 

When I console logged my data, I found that my data was structured as
![image](https://user-images.githubusercontent.com/64060109/187679556-9939b43e-5519-46b4-bd67-427233cea8f1.png)

So the solution was to use `const data = Object.values(result)` and pass the data to the `exportFromJSON`

**Comment by anil-pamerapu** [comment]
Hi 
Is there any way to add (sep=, ) in an export JSON file top?
for some European users, we are seeing in something diff format.

![image](https://user-images.githubusercontent.com/80319375/211862693-886e19b3-335d-4804-91f3-2cc3a20721cd.png)

add Like this:
![image](https://user-images.githubusercontent.com/80319375/211862909-8a205b4a-7f81-49ef-8fef-00bbb75048f9.png)
