### ISSUE TITLE
How to customize the starting element of XML file?

### ISSUE THREAD

**Issue by skag27** [zheeeng/export-from-json#113]
Hi, may i know is there any way to customize the starting element of the XML output? I mean the base and element tags.

**Comment by zheeeng** [comment]
Sorry for it isn't being supported at present. They are hard-coded internal.

**Comment by zheeeng** [comment]
You can give us some concrete demands for this. After some investigation, we will provide this customization for you.

**Comment by Abhinav-Appleute** [comment]
I need XML to be in ISO 20022 standards (banking ISO standard), can I get it ?

**Comment by zheeeng** [comment]
@Abhinav-Appleute

I will take this in the next release if the request is to convert plain JSON to XML. e.g.

from
```json
{
   "a": { "b": "c", "d": { "e": "f" } }
}
```

to

```xml
<a>
    <b>c</b>
    <d>
        <e>f</e>
    </d>
</a>
```
