### ISSUE TITLE
beforeTableEncode example

### ISSUE THREAD

**Issue by mitrosunay** [zheeeng/export-from-json#115]
Could you please provide the working example of beforeTableEncode prop.
Thanks

**Comment by zheeeng** [comment]
Of course, there is a test case for it: https://github.com/zheeeng/export-from-json/blob/master/__tests__/createTableEntries.spec.ts#L14.

I will update the document later.

**Comment by Tsaukpaetra** [comment]
It would be useful to note that the values passed into the function are pre-stringified. As an example, I had an object with nulls that I was intending to use the beforeTableEncode function to swap out with empty strings, but by the time it was called the nulls had been converted to `'null'`, which was a bit surprising.

**Comment by zheeeng** [comment]
> It would be useful to note that the values passed into the function are pre-stringified. As an example, I had an object with nulls that I was intending to use the beforeTableEncode function to swap out with empty strings, but by the time it was called the nulls had been converted to `'null'`, which was a bit surprising.

It seems that you can fallback nullish values before passed them.

**Comment by Tsaukpaetra** [comment]
Yeah that's what I ended up doing, using a double-loop.
