### ISSUE TITLE
导出文件使用Excel打开中文乱码-最新版

### ISSUE THREAD

**Issue by huangjin0219** [zheeeng/export-from-json#123]
`import ExportFromJson from 'export-from-json'`
`const exportFromJson = (data = [], fileName, exportType = 'csv') => {
  return ExportFromJson({ data, fileName, exportType })
}`
![image](https://user-images.githubusercontent.com/82326428/185727364-766faccd-bd94-40ad-a880-6475d426a8c5.png)
版本使用的最新版

把版本调到1.1.4，导出无乱码情况

新版本做了什么调整吗？还是？

**Comment by zheeeng** [comment]
有复现 demo 吗

**Comment by zheeeng** [comment]
如果是 csv 格式可以传入 withBOM: true

**Comment by huangjin0219** [comment]
> 

最新版本1.6.0 传入这个的确是可以正常导出
但是以前的版本不需要这个字段也是正常的，为什么不默认是true呢，或者说出于什么考虑呢

**Comment by zheeeng** [comment]
https://zh.wikipedia.org/wiki/%E4%BD%8D%E5%85%83%E7%B5%84%E9%A0%86%E5%BA%8F%E8%A8%98%E8%99%9F#UTF-8

使用微软系软件打开时需要这个符号确保不会识别成乱码。一般的使用环境不建议设置添加 BOM 信息。
