### ISSUE TITLE
Column splitting if spaces

### ISSUE THREAD

**Issue by ngajhede** [zheeeng/export-from-json#132]
Hiya. 

Getting a strange error if I only export one column where the value has spaces (in this example, a name).
If I just export the ID (without spaces), it is exported correctly as one column.

Example below (With all fields exported, with just name exported (error) and the array I am feeding the library)
![image](https://user-images.githubusercontent.com/12418495/192731955-c95e02a3-f890-4fae-b6f4-1c46b26cca0a.png)

**Comment by zheeeng** [comment]
Can you provide sample data?

**Comment by ngajhede** [comment]
> Can you provide sample data?

```
[
  {
    name: 'John Doe',
  },
  {
    name: 'Jane Doe',
  },
  {
    name: 'John Smith',
  },
  {
    name: 'Jane Smith',
  },
]
```

**Comment by ngajhede** [comment]
Another note: Just tested with XLS which worked fine. The issue here is with CSV export 😄

**Comment by zheeeng** [comment]
I tested your data and got the expected output.

![image](https://user-images.githubusercontent.com/1303154/192762034-163f9424-9fdd-4309-a36d-c4111e31d389.png)

**Comment by ngajhede** [comment]
> I tested your data and got the expected output.
> 
> ![image](https://user-images.githubusercontent.com/1303154/192762034-163f9424-9fdd-4309-a36d-c4111e31d389.png)

I just tested in two toher spreadsheet programs, works now. My fault. Thank you!
