### ISSUE TITLE
Can we add sep=, on first line of exported csv?

### ISSUE THREAD

**Issue by anil-pamerapu** [zheeeng/export-from-json#136]
Hi
Is there any way to add (sep=, ) in an export JSON file top?
for some European users, we are seeing in something diff format.
like this way:
![image](https://user-images.githubusercontent.com/80319375/211863383-f7380b9b-c41d-42e9-94ad-56dc9286bfe0.png)

for European users: 

![image](https://user-images.githubusercontent.com/80319375/211863535-460d91b7-6eb9-4fd5-ba2e-3159e2a3bb44.png)

**Comment by zheeeng** [comment]
The processor proxy will solve your problem.

Pass this option:

```
      processor: (content, ...args) => exportFromJSON.processors.downloadFile('sep=,\n' + content, ...args)
```

**Comment by anil-pamerapu** [comment]
In which file we need to update this one
means were exactly

**Comment by anil-pamerapu** [comment]
data we are getting in json formate
