### ISSUE TITLE
Undefined delimiter on csv export

### ISSUE THREAD

**Issue by Edfrost321** [zheeeng/export-from-json#141]
I am finding that even simple examples can no longer export as csv.

I am using MS Edge Version 110.0.1587.41 (Official build) (64-bit)

To save any complications I tried using the demo from your Github examples. The column headers work but the data is no longer separated by commas and instead shows 'undefined' between the values.

Please see code example here:
https://jsfiddle.net/u9Lkp357/

I have also tried this in chrome, with the same result.

Please advise.
![image](https://user-images.githubusercontent.com/46543651/218671376-3a706fed-2c21-486f-83b7-b3cba0159ed6.png)

![image](https://user-images.githubusercontent.com/46543651/218671488-1d20d9f3-9800-4590-8db7-0a7c35a347ab.png)

Kind regards

Ed

**Comment by zheeeng** [comment]
Sorry for missing the overall testing for the new option `delimiter `. Try 1.7.2 fixed this bug.

**Comment by Edfrost321** [comment]
Sorted, thank you.

And thank you for such a useful tool, it has been integral to my business' software :)

Ed
