### ISSUE TITLE
Excel file with corrupt message

### ISSUE THREAD

**Issue by parrajr** [zheeeng/export-from-json#145]
Hi,

I'm using the tool and when I export a JSON to Excel, it works properly. But, when the user opens the excel file, a message saying the file is corrupted is shown from Excel. If you open it anyway, file is ok, but I want to avoid that message. Anything I can do?

Thanks for the attention.

**Comment by zheeeng** [comment]
I apologize for the inconvenience caused. `export-from-json` only provides a lightweight format conversion solution. There may not be anything that can be done to eliminate the warning message in Excel. If you need a more powerful and flexible solution for generating Excel files, I recommend using the xlsx package.
