### ISSUE TITLE
XML 元素内部定义属性

### ISSUE THREAD

**Issue by HH-hexiao** [zheeeng/export-from-json#147]
怎么在XML 元素内部定义属性呢 json 格式的话

**Comment by zheeeng** [comment]
can you please explain it in more detail?

**Comment by HH-hexiao** [comment]
<a  c="23232">5</a>  这种json怎么生成

**Comment by HH-hexiao** [comment]
`<a b="123">1<a>` 这种怎么生成

**Comment by zheeeng** [comment]
能否提供完整的转换数据及调用参数？
比如要导处的格式是什么？是 json 吗? 
传入的 data 是什么，包含了 `<a b="123">1<a>` 有什么问题？
什么是在 “在XML 元素内部定义属性”，你需要的是什么功能？
