### ISSUE TITLE
xls export is giving output without table structure.

### ISSUE THREAD

**Issue by kunal1697** [zheeeng/export-from-json#173]
I am trying to export file type xsl but after the export the file is getting generated but the Excel table structure is gone will get Excel will blank white sheet with values.

**Comment by zheeeng** [comment]
Can you provide a copy of the sample data?

**Comment by kunal1697** [comment]
`[
    {
        "ID": 38,
        "SNAPSHOT_DATE": "2022-06-30T00:00:00",
        "LOT_NUMBER": "HASUL100",
        "FUNDFAMILY_NAME": "SLGI Asset Management Inc.",
        "LAST_UPDATED_DATE": "2020-05-15T00:00:00",
        "STATUS_ID": 1,
        "ETA_WORKING_DAY": 11,
        "ETA_EXPECTED_DATE": "2023-02-15T00:00:00",
        "TOTAL_EXPECTED_FUND": 144,
        "COMMENTS": null,
        "FREQUENCY_TYPE": "Monthly",
        "Status": "True"
    },
    {
        "ID": 97,
        "SNAPSHOT_DATE": "2022-06-30T00:00:00",
        "LOT_NUMBER": "HATHR100",
        "FUNDFAMILY_NAME": "Thornburg Investment Management",
        "LAST_UPDATED_DATE": "2020-05-15T00:00:00",
        "STATUS_ID": 1,
        "ETA_WORKING_DAY": 11,
        "ETA_EXPECTED_DATE": "2023-02-15T00:00:00",
        "TOTAL_EXPECTED_FUND": 27,
        "COMMENTS": null,
        "FREQUENCY_TYPE": "Monthly",
        "Status": "True"
    }
] ` this is my json data.  



This is my code:

```
`const fileName = `MonthlyStaging_${new Date().toJSON().slice(0, 10)}`

const exportType = exportFromJSON.types.xls     

const monthlyStagingData = data.data.map(e => ({

        "Snapshot_Date": e.SNAPSHOT_DATE == null ? "-" : moment(e.SNAPSHOT_DATE).format(

          "YYYY-MM-DD"),

        "Lot_No": e.LOT_NUMBER == null ? "-" : e.LOT_NUMBER,

        "Fund_Family": e.FUNDFAMILY_NAME == null ? "-" : e.FUNDFAMILY_NAME,

        "Last_Updated_Date": e.LAST_UPDATED_DATE == null ? "-" : moment(e.LAST_UPDATED_DATE).format(

          "YYYY-MM-DD"),

        "ETA_Working_Day": e.ETA_WORKING_DAY == null ? "-" : moment(e.ETA_WORKING_DAY).format(

          "YYYY-MM-DD"),

        "ETA_Exp_Day": e.ETA_EXPECTED_DATE == null ? "-" : moment(e.ETA_EXPECTED_DATE).format(

          "YYYY-MM-DD"),

        "Total_Exp_Fund": e.TOTAL_EXPECTED_FUND == null ? "-" : e.TOTAL_EXPECTED_FUND,

        "Status": e.STATUS_ID == null ? "-" : e.STATUS_ID,

        "Frequency": e.FREQUENCY_TYPE == null ? "-" : e.FREQUENCY_TYPE

      }))



 

    exportFromJSON({ data: monthlyStagingData, fileName: fileName, exportType: exportType });`
```

This is is my dependent version
"export-from-json":"^1.7.2"

**Comment by kunal1697** [comment]
Ok I have tested it there was some problem with Microsoft excel you can close the issue thanks
