### ISSUE TITLE
Add Specfic  Column Title

### ISSUE THREAD

**Issue by AMohamedRaafat** [zheeeng/export-from-json#245]
i have issue when exporting in coulmn title back with the key 
i need to change it to other title not key 
how to do this

**Comment by AMohamedRaafat** [comment]
@zheeeng

**Comment by zheeeng** [comment]
Try use `beforeTableEncode` to convert rows to new rows.

beforeTableEncode: rows => rows.map(row => ({ fieldName: row.fieldName === 'foo' : 'bar' : row.fieldName, ...row })),
