### ISSUE TITLE
Support for multiple pages

### ISSUE THREAD

**Issue by Codemaine** [zheeeng/export-from-json#335]
For exporting to XLS, there should be an option to create multiple pages. We could pass an array of the data, and the name of the page, to generate pages in the Excel file for the provided data.

<img width="425" alt="image" src="https://github.com/zheeeng/export-from-json/assets/64845752/8b05f8d5-a736-431a-a5bb-54b86ccd7f7b">

**Comment by zheeeng** [comment]
This feature is not planned at present coz of implementation limitation.
