### ISSUE TITLE
Add xlsx as supported file type for newer versions

### ISSUE THREAD

**Issue by sahshaurya** [zheeeng/export-from-json#34]
Can 'xlsx' also be added as an extension type apart for xls?

xls files can no longer be smoothly opened in Excel and gives the user a warning that the file may be corrupted.

**Comment by zheeeng** [comment]
`xlsx` and `xls` is far more complex and actually the exported `xls` file is not with the `xls` content, it is the `html` which cloud be opened by `xls` reader. It's known issue and has no ideal solutions at present.

Thx for your using.

**Comment by Rahulk4128** [comment]
any update on this?
@zheeeng
