### ISSUE TITLE
Export as xls and html does not work properly

### ISSUE THREAD

**Issue by antoanetaDi** [zheeeng/export-from-json#347]
I try to export xls file from json and I use the code below:
  const exportXLS = () => {
      exportFromJSON({
            data: data,
            fileName: 'xlsDownload',
            exportType: 'xls',
        });
    };

Expected: excel file with Sheets
Result: The library generates an HTML table in a file with extension .xls. 

I have the same problem, when I try to generate a html file. I use the code:
 const exportHTML = () => {
        exportFromJSON({
            data: data,
            fileName: 'htmlDownload',
            exportType: 'html',
        });
    };
Expected: HTML table with the data. 
Result: The library generates a file with extension .html, but the file contains the raw data, not the html code.

My question is am i doing something wrong to get these wrong formats in the end or is this a bug?

**Comment by Rahulk4128** [comment]
This library should add support for xlxs file too?

**Comment by zheeeng** [comment]
> I try to export xls file from json and I use the code below: const exportXLS = () => { exportFromJSON({ data: data, fileName: 'xlsDownload', exportType: 'xls', }); };
> 
> Expected: excel file with Sheets Result: The library generates an HTML table in a file with extension .xls.
> 
> I have the same problem, when I try to generate a html file. I use the code: const exportHTML = () => { exportFromJSON({ data: data, fileName: 'htmlDownload', exportType: 'html', }); }; Expected: HTML table with the data. Result: The library generates a file with extension .html, but the file contains the raw data, not the html code.
> 
> My question is am i doing something wrong to get these wrong formats in the end or is this a bug?



> I try to export xls file from json and I use the code below: const exportXLS = () => { exportFromJSON({ data: data, fileName: 'xlsDownload', exportType: 'xls', }); };
> 
> Expected: excel file with Sheets Result: The library generates an HTML table in a file with extension .xls.
> 
> I have the same problem, when I try to generate a html file. I use the code: const exportHTML = () => { exportFromJSON({ data: data, fileName: 'htmlDownload', exportType: 'html', }); }; Expected: HTML table with the data. Result: The library generates a file with extension .html, but the file contains the raw data, not the html code.
> 
> My question is am i doing something wrong to get these wrong formats in the end or is this a bug?

It works as expected. The exported type are configured to output the standard format which's raw content obeys the  `Content-Type` definition. You are not need to care about its concrete content.

> This library should add support for xlxs file too?

It doesn't planned.
