### ISSUE TITLE
New line in a string

### ISSUE THREAD

**Issue by rainercedric23** [zheeeng/export-from-json#55]
Is there a way I could enter a new line for a specific string?  what I am currently doing is like this

    exportedData = {test: 'test\ntest'}
    exportFromJson({ data: exportedData, fileName: 'foo', exportType: 'xls' });

but the exported file will just create a space and not new line in a cell

**Comment by zheeeng** [comment]
sorry for this is not be supported

**Comment by gcarpi** [comment]
Use `<br style="mso-data-placement:same-cell;" />` to break line in a string
