### ISSUE TITLE
Is it possible to generate an excel table in this format?

### ISSUE THREAD

**Issue by launbraun** [zheeeng/export-from-json#66]
Hello, please tell me if there is a possibility with the help of "export-from-json" export the data in this form? Sorry if I asked a question in the wrong topic.

![Screenshot](https://user-images.githubusercontent.com/37041563/120670053-b2df8c00-c498-11eb-8bac-f105827b8dc5.jpg)

**Comment by zheeeng** [comment]
Sorry for this isn't our feature yet.
