### ISSUE TITLE
Can't export unknown data type xlsx

### ISSUE THREAD

**Issue by gmarshall56** [zheeeng/export-from-json#71]
.xlsx is a valid Excel file format. 

I'm using your API per the sample I found [here](https://www.c-sharpcorner.com/article/export-json-data-to-excel-in-react-application/).

The code breaks when you set the exportType  to 'xlsx'.

![exportFromJsonError](https://user-images.githubusercontent.com/5943189/128884089-b6b7eaae-1599-4f93-b224-11b3f7ca8bad.JPG)

Thank you.

**Comment by zheeeng** [comment]
https://www.npmjs.com/package/xlsx is suggested for generating `xlsx` format sheet.
