### ISSUE TITLE
Format and extension do not match

### ISSUE THREAD

**Issue by ShinyCoconut** [zheeeng/export-from-json#73]
![image](https://user-images.githubusercontent.com/40281674/132856653-35454720-02c7-4082-958a-ea057677e182.png)

Is there a way to make things in order for this message not to appear?

Thanks

**Comment by zheeeng** [comment]
At present, I didn't find the solution for fixing.

**Comment by ShinyCoconut** [comment]
I don't believe closing the issue is the solution 👍🏻

**Comment by fabriciosautner** [comment]
Same problem
