### ISSUE TITLE
error on line 4 at column 11: Opening and ending tag mismatch: meta line 3 and head

### ISSUE THREAD

**Issue by sknightq** [zheeeng/export-from-json#76]
The error is coming when I using `new DOMParser().parseFromString()` to parse the content. 
You should use the closing tag in the HTML template.
From 
```<meta charset="UTF-8">```
To
```<meta charset="UTF-8" />```
In **converters.ts** at line 164

**Comment by zheeeng** [comment]
fixed in v1.4.1
